name: Measure Coverage

on:
  workflow_dispatch:
  pull_request:
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add coverage report to PR
        uses: krogerco/Shared-CI-Action-Android/.github/actions/code-coverage@v1.1.0
        with:
          java_version: 17
          gradle_command: ':app:koverXmlReport'
          path: ${{ github.workspace }}/app/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update_comment: true
        env:
          KT_JFROG_USERID: "${{ secrets.KT_JFROG_USERID }}"
          KT_JFROG_TOKEN: "${{ secrets.KT_JFROG_TOKEN }}"
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
